# Generated by Django 2.2.6 on 2019-12-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
