# Generated by Django 2.2.6 on 2019-12-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='counter',
            field=models.BooleanField(default=False),
        ),
    ]
