# Generated by Django 2.2.9 on 2019-12-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191220_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
