# Generated by Django 2.2.15 on 2020-08-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
