# Generated by Django 2.2.15 on 2020-08-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_machine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='picture',
            field=models.ImageField(null=True, upload_to='machines'),
        ),
    ]
